--Tables
DROP TABLE IF EXISTS "brand_models";
DROP TABLE IF EXISTS "brands";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "roles";
DROP TABLE IF EXISTS "cities";
DROP TABLE IF EXISTS "regions";
DROP TABLE IF EXISTS "sliders"
