is_debug: true
listen:
  type: port
  port: :8080
  bind_ip: 0.0.0.0
swagger:
  version: 1.0
  service_name: AutoTM-Admin.
  title: AutoTM-Admin
  host: 127.0.0.1:8080
storage:
  psql:
    host: 127.0.0.1
    port: 5432
    database: autotm_admin
    username: autotm
    password: autotm
    pg_pool_max_conn: 400
    migration: true
log:
  path:   /home/user/Desktop/sada/autotm-admin/logs
  filename: autotm-admin.log
file_path: /home/user/Desktop/sada/autotm-admin/uploads
auth:
  jwt_verify: verify!autm25tm#a?aa
  jwt_registration: registration!autm25tm#a?aa

