is_debug: true
listen:
  type: port
  port: :2030
  bind_ip: 0.0.0.0
swagger:
  version: 1.0
  service_name: AutoTM-Admin.
  title: AutoTM-Admin
  host: 127.0.0.1:2030
storage:
  psql:
    host: 127.0.0.1
    port: 5432
    database: autotm
    username: autotm
    password: autotm
    pg_pool_max_conn: 400
    migration: true
log:
  path:   /home/user/Desktop/sada/autotm-admin/logs
  filename: autotm-admin.log
file_path: /home/user/Desktop/sada/autotm-admin/uploads
auth:
  jwt_verify: verify!autm25tm#a?aa
  jwt_registration: registration!autm25tm#a?aa
minio:
  endpoint: 10.192.1.127:9000
  access_key_id: minioadmin
  secret_access_key: minioadmin
  
user_service: http://10.192.5.57:8002/autotm/user-service