package models

type Car struct {
	Id             int64
	UserId         int64
	UserName       string
	StockId        int64
	StoreName      string
	BrandId        int64
	BrandName      string
	ModelId        int64
	ModelName      string
	Year           int64
	Mileage        int64
	Color          string
	EngineCapacity float64
	EngineType     string
	BodyId         int64
	BodyNameTM     string
	BodyNameEN     string
	BodyNameRU     string
	Transmission   string
	DriverType     string
	Vin            string
	Description    string
	CityId         int64
	CityNameTM     string
	CityNameEN     string
	CityNameRU     string
	Name           string
	Mail           string
	PhoneNumber    string
	Price          int64
	IsComment      bool
	IsExchange     bool
	IsCredit       bool
	Images         interface{}
	Status         string
}

type Truck struct {
	Id              int64
	UserId          int64
	UserName        string
	StockId         int64
	StoreName       string
	BodyId          int64
	BodyNameTM      string
	BodyNameEN      string
	BodyNameRU      string
	BrandId         int64
	BrandName       string
	ModelId         int64
	ModelName       string
	LoadCapacity    float64
	Price           int64
	BodyType        string
	DriveType       string
	Transmission    string
	EngineType      string
	Year            int64
	Seats           int64
	CabType         string
	WheelFormula    string
	Chassis         string
	CabSuspension   string
	BusType         string
	SuspensionType  string
	Brakes          string
	Axles           int64
	EngineHours     int64
	VehicleType     string
	EngineCapacity  float64
	ForkliftType    string
	LiftingCapacity int64
	Mileage         int64
	ExcavatorType   string
	BulldozerType   string
	Color           string
	Vin             string
	Description     string
	CityId          int64
	CityNameTM      string
	CityNameEN      string
	CityNameRU      string
	Name            string
	Mail            string
	PhoneNumber     string
	IsComment       bool
	IsExchange      bool
	IsCredit        bool
	Images          interface{}
	Status          string
}
